// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Matches bus operators based on user's origin, destination, and preferred travel time.
 *
 * - matchOperator - A function that handles the operator matching process.
 * - MatchOperatorInput - The input type for the matchOperator function.
 * - MatchOperatorOutput - The return type for the matchOperator function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MatchOperatorInputSchema = z.object({
  origin: z.string().describe('The origin city for the bus journey.'),
  destination: z.string().describe('The destination city for the bus journey.'),
  preferredTravelTime: z
    .string()
    .describe('The preferred travel time, e.g., morning, afternoon, or evening.'),
});
export type MatchOperatorInput = z.infer<typeof MatchOperatorInputSchema>;

const MatchOperatorOutputSchema = z.object({
  operatorName: z.string().describe('The name of the recommended bus operator.'),
  contactInformation: z
    .string()
    .describe('Contact information for the recommended bus operator.'),
  estimatedFare: z.number().describe('The estimated fare for the bus journey.'),
  busType: z.string().describe('The type of bus offered by the operator.'),
});
export type MatchOperatorOutput = z.infer<typeof MatchOperatorOutputSchema>;

export async function matchOperator(input: MatchOperatorInput): Promise<MatchOperatorOutput> {
  return matchOperatorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'matchOperatorPrompt',
  input: {schema: MatchOperatorInputSchema},
  output: {schema: MatchOperatorOutputSchema},
  prompt: `You are an expert bus operator recommendation system.

You will receive the origin, destination, and preferred travel time from the user.
Based on this information, recommend a suitable bus operator.

Origin: {{{origin}}}
Destination: {{{destination}}}
Preferred Travel Time: {{{preferredTravelTime}}}

Consider factors such as the operator's service area, bus types, and estimated fares to provide the best recommendation.

Ensure the output is a valid JSON object conforming to the MatchOperatorOutputSchema.`,
});

const matchOperatorFlow = ai.defineFlow(
  {
    name: 'matchOperatorFlow',
    inputSchema: MatchOperatorInputSchema,
    outputSchema: MatchOperatorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
